//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumentos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersion
    {
        public int version_id { get; set; }
        public System.Guid row_id { get; set; }
        public int document_id { get; set; }
        public int version_number { get; set; }
        public byte[] file_content { get; set; }
        public Nullable<long> file_size_in_bytes { get; set; }
        public Nullable<System.DateTime> uploaded_at { get; set; }
        public int uploading_user_id { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Users Users { get; set; }
    }
}
