//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumentos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public Documents()
        {
            this.UserDocumentAccess = new HashSet<UserDocumentAccess>();
            this.DocumentVersion = new HashSet<DocumentVersion>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string file_extension { get; set; }
        public int owner_user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ICollection<UserDocumentAccess> UserDocumentAccess { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<DocumentVersion> DocumentVersion { get; set; }
    }
}
