//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumentos.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GestionDocumentosEntities : DbContext
    {
        public GestionDocumentosEntities()
            : base("name=GestionDocumentosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DocumentAccess> DocumentAccess { get; set; }
        public DbSet<Documents> Documents { get; set; }
        public DbSet<DocumentVersion> DocumentVersion { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<UserDocumentAccess> UserDocumentAccess { get; set; }
        public DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> sp_CreateUser(string firstName, string lastName, string email, string passwordHash, Nullable<int> roleId)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_CreateUser", firstNameParameter, lastNameParameter, emailParameter, passwordHashParameter, roleIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_UploadNewDocument(string name, string fileExtension, Nullable<int> ownerUserId, byte[] fileContent, Nullable<long> fileSizeInBytes)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var fileExtensionParameter = fileExtension != null ?
                new ObjectParameter("FileExtension", fileExtension) :
                new ObjectParameter("FileExtension", typeof(string));
    
            var ownerUserIdParameter = ownerUserId.HasValue ?
                new ObjectParameter("OwnerUserId", ownerUserId) :
                new ObjectParameter("OwnerUserId", typeof(int));
    
            var fileContentParameter = fileContent != null ?
                new ObjectParameter("FileContent", fileContent) :
                new ObjectParameter("FileContent", typeof(byte[]));
    
            var fileSizeInBytesParameter = fileSizeInBytes.HasValue ?
                new ObjectParameter("FileSizeInBytes", fileSizeInBytes) :
                new ObjectParameter("FileSizeInBytes", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_UploadNewDocument", nameParameter, fileExtensionParameter, ownerUserIdParameter, fileContentParameter, fileSizeInBytesParameter);
        }
    
        public virtual ObjectResult<sp_DownloadDocument_Result> sp_DownloadDocument(Nullable<int> documentId, Nullable<int> version)
        {
            var documentIdParameter = documentId.HasValue ?
                new ObjectParameter("DocumentId", documentId) :
                new ObjectParameter("DocumentId", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("Version", version) :
                new ObjectParameter("Version", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DownloadDocument_Result>("sp_DownloadDocument", documentIdParameter, versionParameter);
        }
    
        public virtual ObjectResult<sp_GetDocumentsByUser_Result> sp_GetDocumentsByUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDocumentsByUser_Result>("sp_GetDocumentsByUser", userIdParameter);
        }
    }
}
