//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumentos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDocumentAccess
    {
        public int id { get; set; }
        public int document_id { get; set; }
        public int access_granted_to_user_id { get; set; }
        public int permission_id { get; set; }
        public int access_granted_by_user_id { get; set; }
    
        public virtual DocumentAccess DocumentAccess { get; set; }
        public virtual Documents Documents { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
