//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumentos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Documents = new HashSet<Documents>();
            this.DocumentVersion = new HashSet<DocumentVersion>();
            this.UserDocumentAccess = new HashSet<UserDocumentAccess>();
            this.UserDocumentAccess1 = new HashSet<UserDocumentAccess>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string institutional_email { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
    
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual ICollection<DocumentVersion> DocumentVersion { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<UserDocumentAccess> UserDocumentAccess { get; set; }
        public virtual ICollection<UserDocumentAccess> UserDocumentAccess1 { get; set; }
    }
}
